### ISSUE TITLE
Required "pg_trgm" extension on all catalogs

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrest#4]
New catalogs require the gp_trgm extension on the back end postgresql database. Without it, clients will get an 'internal server error' and in the /var/log/httpd/ssl_error_log will see the following message within the stack trace logged by ERMrest.

'got exception "operator class "gin_trgm_ops" does not exist for access method "gin"\\n" during model introspection'

The complete stack trace is:

[Wed Jul 01 15:22:05 2015] [error] [client ::1] Traceback (most recent call last):
[Wed Jul 01 15:22:05 2015] [error] [client ::1]   File "/usr/lib/python2.6/site-packages/web/application.py", line 239, in process
[Wed Jul 01 15:22:05 2015] [error] [client ::1]     return self.handle()
[Wed Jul 01 15:22:05 2015] [error] [client ::1]   File "/usr/lib/python2.6/site-packages/web/application.py", line 230, in handle
[Wed Jul 01 15:22:05 2015] [error] [client ::1]     return self._delegate(fn, self.fvars, args)
[Wed Jul 01 15:22:05 2015] [error] [client ::1]   File "/usr/lib/python2.6/site-packages/web/application.py", line 405, in _delegate
[Wed Jul 01 15:22:05 2015] [error] [client ::1]     return handle_class(f)
[Wed Jul 01 15:22:05 2015] [error] [client ::1]   File "/usr/lib/python2.6/site-packages/web/application.py", line 396, in handle_class
[Wed Jul 01 15:22:05 2015] [error] [client ::1]     return tocall(*args)
[Wed Jul 01 15:22:05 2015] [error] [client ::1]   File "/usr/lib/python2.6/site-packages/ermrest/ermrest_apis.py", line 283, in GET
[Wed Jul 01 15:22:05 2015] [error] [client ::1]     return self.METHOD('GET')
[Wed Jul 01 15:22:05 2015] [error] [client ::1]   File "/usr/lib/python2.6/site-packages/ermrest/ermrest_apis.py", line 250, in METHOD
[Wed Jul 01 15:22:05 2015] [error] [client ::1]     first = result.next()
[Wed Jul 01 15:22:05 2015] [error] [client ::1]   File "/usr/lib/python2.6/site-packages/ermrest/sanepg2.py", line 146, in pooled_perform
[Wed Jul 01 15:22:05 2015] [error] [client ::1]     result = bodyfunc(conn, cur)
[Wed Jul 01 15:22:05 2015] [error] [client ::1]   File "/usr/lib/python2.6/site-packages/ermrest/url/ast/data/path.py", line 191, in wrapbody
[Wed Jul 01 15:22:05 2015] [error] [client ::1]     return body(conn, cur)
[Wed Jul 01 15:22:05 2015] [error] [client ::1]   File "/usr/lib/python2.6/site-packages/ermrest/url/ast/model.py", line 69, in body
[Wed Jul 01 15:22:05 2015] [error] [client ::1]     return self.catalog.manager.get_model(cur)
[Wed Jul 01 15:22:05 2015] [error] [client ::1]   File "/usr/lib/python2.6/site-packages/ermrest/catalog.py", line 251, in get_model
[Wed Jul 01 15:22:05 2015] [error] [client ::1]     raise ValueError('Introspection on existing catalog failed (likely a policy mismatch): %s' % str(te))
[Wed Jul 01 15:22:05 2015] [error] [client ::1] ValueError: Introspection on existing catalog failed (likely a policy mismatch): operator class "gin_trgm_ops" does not exist for access method "gin"

So it appears that we now require this extension by default but we do not create new catalogs (databases) with the extension enabled.

**Comment by robes** [comment]
The workaround for now is to add this extension manually after you have created a new catalog.

1. switch to the *postgres* superuser

  ```
  $ sudo su - postgres
  ```

2. connect to the *ermrest* master database which contains the ERMrest registry

  ```
  -bash-4.1$ psql ermrest
  psql (9.4.4)
  Type "help" for help.
  ```

3. query the *simple_registry* to discover the random database names of your catalogs

  ```
  ermrest=# select * from ermrest.simple_registry;
   id |                            descriptor                             
  ----+-------------------------------------------------------------------
    1 | {"type": "postgres", "dbname": "_ermrest_RANDOM"}
  (1 row)
  ```

4. connect to the catalog database

  ```
  ermrest=# \connect _ermrest_RANDOM
  You are now connected to database "_ermrest_RANDOM" as user "postgres".
  ```

5. enable the pg_tgm extension

  ```
  _ermrest_RANDOM=# create extension pg_trgm with schema pg_catalog;
  CREATE EXTENSION
  ```

6. verify that it is installed

  ```
  _ermrest_RANDOM=#  \dx
                                      List of installed extensions
    Name   | Version |   Schema   |                            Description                            
  ---------+---------+------------+-------------------------------------------------------------------
   pg_trgm | 1.1     | pg_catalog | text similarity measurement and index searching based on trigrams
   plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
  (2 rows)
  ```

7. you are done

  ```
  _ermrest_RANDOM=#  \q
  ```

You should be able to use the ERMrest catalog now.

**Comment by robes** [comment]
We need to install this extension by default for all new catalogs assuming this is a feature we want on by default.

We should be able to do this by changing the create catalog operation to create the backend database based on a template database, and the template database to have the pg_trgm extension installed already.
